### ISSUE TITLE
`tzdata` is actually required, not optional

### ISSUE THREAD

**Issue by ericlathrop** [kipcole9/astro#4]
I'm using `tz` in my project instead of `tzdata`, and when I added `astro` my app would no longer start.

The error was:
`** (Mix) Could not start application hackney: could not find application file: hackney.app`

I'm guessing the issue is from this line: https://github.com/kipcole9/astro/blob/eb6018e56ddf1931c2b3e02acd17358062dc5602/lib/astro/time.ex#L762

I'd like to not have 2 time zone databases in my project.

BTW, this project is awesome. I'm so glad I didn't have to write it myself!

**Comment by kipcole9** [comment]
@ericlathrop thanks for the issue and apologies for the inconvenience. And also for the diagnosis. I'll sort this out but it might take 24 hours to get a new release out.

Also really happy you're getting value from this lib. I had to implement it so I could implement Lunisolar calendars - but it got a life of its own. I learnt a lot of things I didn't know. But that also means feedback and bug reports are really important so thats for taking the time to do that.

**Comment by kipcole9** [comment]
Also I've love to know what you're using Astro for, if you're able to share.

**Comment by ericlathrop** [comment]
Thanks for the respons!

I wonder if you can compute the time zone offset just using the built in DateTime stuff. Like `local_time - utc_now`.

I'm building a toy home automation / personal agent / workflow tool. My use case is something like "turn on the lights at sunset". It's really early so still private.

**Comment by kipcole9** [comment]
Sounds a cool project, I hope to hear more about it when you're done.  I've pushed [a commit](https://github.com/kipcole9/astro/commit/6d92891ec1c1448adc8f509c21ee869da0a54b23) that fixes this issue by using only the `Calendar.TimeZoneDatabase` behaviour and the time zone database configured for the system. That way any time zone database can be used as long as it complies with the behaviour. 

There is some more work to do before I can release a new version:
1. 2 tests are now failing which need fixing
2. I need to test and confirm that its ok to not configure either `tz` or `tzdata` since there are no direct calls to these modules any more.

The good news is that the code now reflects the documentation in the README!
